FROM ubuntu:16.04
RUN apt-get update \
    && apt-get install -y pdns-recursor
ADD recursor.conf /etc/powerdns

ENTRYPOINT /usr/sbin/pdns_recursor
CMD "--daemon=no --write-pid=no --disable-syslog --log-timestamp=no"
